# Generated by Django 5.2.5 on 2025-09-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionmaker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='decisionmaker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='decisionmaker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='decisionmaker',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='decisionmaker',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='decisionmaker',
            name='title',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='field',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='job_url',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='source_portal',
        ),
        migrations.AddField(
            model_name='decisionmaker',
            name='decision_maker_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Decision Maker Email'),
        ),
        migrations.AddField(
            model_name='decisionmaker',
            name='decision_maker_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Decision Maker LinkedIn'),
        ),
        migrations.AddField(
            model_name='decisionmaker',
            name='decision_maker_name',
            field=models.CharField(default='', max_length=255, verbose_name='Decision Maker Name'),
        ),
        migrations.AddField(
            model_name='decisionmaker',
            name='decision_maker_title',
            field=models.CharField(default='', max_length=255, verbose_name='Decision Maker Title'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Size'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_url',
            field=models.URLField(blank=True, null=True, verbose_name='Company URL'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_link',
            field=models.URLField(default='', verbose_name='Job Link'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source_job_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.jobportal', verbose_name='Source Job Portal'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_title',
            field=models.CharField(default='', max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='market',
            field=models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom')], default='USA', max_length=3, verbose_name='Market (USA/UK)'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='posted_date',
            field=models.DateField(verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='date_range',
            field=models.CharField(choices=[('24hours', 'Last 24 hours'), ('week', 'Last 7 days'), ('month', 'Last 30 days'), ('all', 'All time')], default='week', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='market',
            field=models.CharField(blank=True, choices=[('USA', 'United States'), ('UK', 'United Kingdom')], max_length=3, null=True),
        ),
    ]
