# Generated by Django 5.2.5 on 2025-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_decisionmaker_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionmaker',
            name='decision_maker_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Decision Maker Phone'),
        ),
    ]
